# -*- coding: utf-8 -*-
"""EXNO1-DS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VqUpPfIJbcJUK0IsjCi8TmUIc7T2tVCa
"""
#Data Cleaning Process
import pandas as pd
df=pd.read_csv("Data_set.csv")
df
df.head()
df.tail()
df.isnull()
df.isnull().sum()
df.describe()
df.dropna(axis=1)
df.dropna(axis=0)
df.fillna(0)
#IQR
import pandas as pd
import seaborn as sns
age=[1,3,28,27,25,92,30,39,40,50,26,24,29,94]
af=pd.DataFrame(age)
af
sns.boxplot(data=af)
sns.scatterplot(data=af)
q1=af.quantile(0.25)
q2=af.quantile(0.5)
q3=af.quantile(0.75)
iqr=q3-q1
iqr=af.quantile(0.5)
low=q1-1.5*iqr
low
high=q3+1.5*iqr
high
aq=af[((af>=low)&(af<=high))]
aq.dropna()
sns.boxplot(data=aq)
sns.scatterplot(data=aq)
#Z SCORE METHOD
import pandas as pd
import numpy as np
import seaborn as sns
import pandas as pd
from scipy import stats
data = {'weight':[12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,202,72,75,78,81,84,232,87,90,93,96,99,258]}
df=pd.DataFrame(data)
df
sns.boxplot(data=df)
z = np.abs(stats.zscore(df))
print(df[z['weight']>3])
val =[12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,202,72,75,78,81,84,232,87,90,93,96,99,258]
out=[]
def d_o(val):
    ts=3
    m=np.mean(val)
    sd=np.std(val)
    for i in val:
        z=(i-m)/sd
        if np.abs(z)>ts:
            out.append(i)
        return out
op = d_o(val)
op